{% set name = "python-language-server" %}
{% set version = "0.36.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c85d718ef6860319ad59fd6f2acb1166e9349b782ee8e8908e08ecf241615f52

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyls = pyls.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - jedi >=0.17.0,<0.18.0a0
    - python-jsonrpc-server >=0.4.0
    - pycodestyle >=2.6.0,<2.7.0
    - pydocstyle >=2.0.0
    - pyflakes >=2.2.0,<2.3.0
    - pylint
    - python >=3.6
    - yapf
    - pluggy
    - autopep8
    - mccabe >=0.6.0,<0.7.0
    - setuptools
    - rope >=0.10.5
    - flake8 >=3.8.0
    - ujson >=3.0

test:
  requires:
    - pip
  commands:
    - python -m pip check
    - pyls --help

about:
  home: https://github.com/palantir/python-language-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 2.7 and 3.4+ implementation of the Language Server Protocol
    making use of Jedi, pycodestyle, Pyflakes and YAPF.
  dev_url: https://github.com/palantir/python-language-server

extra:
  recipe-maintainers:
    - goanpeca
    - ccordoba12
    - rlaverde
    - andfoy
