{% set name = "python-language-server" %}
{% set version = "0.19.0" %}
{% set hash_type = "sha256" %}
{% set hash = "0c55a1936a591457eeb924455919173aca67145ca1bcc9b9f4c725451a1bed81" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/palantir/{{ name }}/archive/{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pyls = pyls.__main__:main
    # This recipe has pyls entrypoints

requirements:
  build:
    - python
    - setuptools
  run:
    - configparser  # [py27 or py34]
    - future >=0.14
    - jedi >=0.10
    - json-rpc
    - pycodestyle
    - pydocstyle >=2.0.0
    - pyflakes >=1.6.0
    - python
    - yapf
    - pluggy
    - autopep8
    - mccabe
    - rope >=0.10.5

test:
  commands:
    - pyls --help

about:
  home: https://github.com/palantir/python-language-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 2.7 and 3.4+ implementation of the Language Server Protocol 
    making use of Jedi, pycodestyle, Pyflakes and YAPF.
  dev_url: https://github.com/palantir/python-language-server

extra:
  recipe-maintainers:
    - goanpeca
    - ccordoba12
    - rlaverde
    - andfoy
    - mariusvniekerk
