{% set name = "python-language-server" %}
{% set version = "0.29.0" %}
{% set hash_type = "sha256" %}
{% set hash = "008a1d4eac857f1b01cea3224503b6656d10833d2e08d6a9da7bde43c55ee33d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyls = pyls.__main__:main
    # This recipe has pyls entrypoints

requirements:
  host:
    - python
    - pip
  run:
    - configparser  # [py27]
    - futures       # [py27]     
    - future >=0.14
    - jedi >=0.15,<0.16
    - python-jsonrpc-server >=0.1.0
    - pycodestyle
    - pydocstyle >=2.0.0
    - pyflakes >=1.6.0
    - pylint
    - python
    - yapf
    - pluggy
    - autopep8
    - mccabe
    - setuptools
    - rope >=0.10.5
    - flake8

test:
  commands:
    - pyls --help

about:
  home: https://github.com/palantir/python-language-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 2.7 and 3.4+ implementation of the Language Server Protocol 
    making use of Jedi, pycodestyle, Pyflakes and YAPF.
  dev_url: https://github.com/palantir/python-language-server

extra:
  recipe-maintainers:
    - goanpeca
    - ccordoba12
    - rlaverde
    - andfoy
    - mariusvniekerk
