travis:
  secure:
    BINSTAR_TOKEN: BIxrHOgVBUUzCczwyigfgfZ4c2hipVbwUJ94VFmHZ8g+qh3p4V1R6RoMgj0HB5Y+1EuBP/HDFMSpFyAQ8Evv0peH8glGOvGMih5YC4yrb34ytlf00JkGUnNvVGpwGdh3mn9rlDmjzWhRYLCJTr9NZMYe5Rhv5U2tT6vPdKpkT/tAv8ejefSJjQzBUiH0WcCNFTL2oFUXIb0FiGz710UM9pI375xs0J0j/HTo5Cq1CZf0ECvfLW4eO2CYl0Mw9RYmwoR/NgVE+3AVxVH2R7KFqyjOofG+yneSoXpiNZ8TJe/MPiqGiI5ehiauBcdophypRlGO4xunS58NIWNrpHPvXpH3y3r6Z/FKiy7YPw3LmahK1XK6pTzSUpe2Nf+MQxLqkOnekzFOhwGuJwAayjYYWwNQ97Z0TWLAMEZwu0M2GSKXgsQ+/wzjcnIzd66bpwkagtyH7OAxeKOPhlBu/mBRBEbC7TgrYymqIh0XHtdLf11bWXwP9JG5LZ761Gw5att0INDwmgMBzYy931qfiiPtjPAAZYcoYn1Oe+YES5YIJ8cX03i4Y/OGC/WZnQcnmwcUk4II51tnUtJqJ6M0NpJL8ex5rrCdb2h9/8hcjGwfAeDajxkF5nieuYJIM61Xl2oQRy5v+st8kchkajBqI2x+fP/LZtik0Oaf4Hqw9hh3M5s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
