travis:
  secure:
    BINSTAR_TOKEN: NScCOxUSisEgDpAxMVcjeq1pAn1uBHvi0KsfE44mr0ur/v7U4Frejra6qWYrssg08zW1gHhzcxr14G9yA9rmLvnfX7jFRVRSFl37Yvi0zXMvkLTeEcOtVr8uwRtXPbY0e/ySxO8dFFEcyFFnaMVuW4DjWu8tSM2idf87u1p+sc2KaHU/78apzF0u+DPndEHPJHvx26aI/UVnuvIqtrOa3uX2EQMCXkyc8TZTQuzbGk6KvHvUICTUgDMN4KSPNSUdOwwTEaKg6WSsmBZCA2AEGh9WR/xhNWmv5q1RU5SpWFxTy5Pmlq2wFq2uXYJoOvKFLmh8gHIYvP2ut2hGwMlol2zuyUtxjtRKTSIuzUR4uXdE0rYTf8doqlmEFN7kbbpMKnBi2lidfcmyyYXZHq9zO4M3VWJDxFHKPfq5Oi2iqRxJthPSbTrPCsIZQGyQt7V1UfDomzRPHiIO1yfE1XWJxKl/PgwtN+aJJXwtyB1CM4i9fY/YIiRuiV89ewlIjor/rJOSgaB7UGjqEs2M10Ozvp7ALH+3MO2UC0lNjAVLcENWG/nlVACvayf5WH9ShRILFzh+V/00Yhvqe8EttW2cyFokSfgWQh5G5qpzdM0Ie5AElA4TBIFP5FFBrrF6WbbPLMZtDa9dreiA8wu/hEo1A2+PGBb8dH6tHbT8sRQecnQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
